apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: visitor-counter
  name: visitor-counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visitor-counter
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: visitor-counter
    spec:
      containers:
      - image: ${IMAGE_NAME}
        name: visitor-counter
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m 
status: {}

